apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    secureJsonData:
      password: otel
    jsonData:
      defaultDatabase: otel
      server: clickhouse
      port: 8123
      protocol: http
      username: otel
      tlsSkipVerify: true
      logs:
        defaultDatabase: otel
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: latest
        timeColumn: Timestamp
        logLevelColumn: SeverityText
        logMessageColumn: Body
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest
        traceIdColumn: TraceId
        spanIdColumn: SpanId
        operationNameColumn: SpanName
        parentSpanIdColumn: ParentSpanId
        serviceNameColumn: ServiceName
        durationColumn: Duration
        durationUnit: nanoseconds
        startTimeColumn: Timestamp
        tagsColumn: SpanAttributes
        serviceTagsColumn: ResourceAttributes
